[package]
name = "shopping_cart"
version = "0.1.0"
authors = ["Wolfgang Grieskamp <wrwg@fb.com>"]
edition = "2021"

[[bin]]
name = "shopping_cart"

[dependencies]
mirai-annotations = { path = "../../annotations" }
contracts = {version = "0.6.2", features = ["mirai_assertions"]}